# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
lane :beta do
  #scan
  #gym(scheme: "MyApp")
  #crashlytics

version  =  get_version_number(xcodeproj: "SwiftPoke.xcodeproj")
increment_version_number(version_number: '1.1.1')

increment_build_number

#versionNumber = get_info_plist_value(path: "SwiftPoke/Info.plist", key: "CFBundleShortVersionString")
#buildNumber = get_info_plist_value(path: "SwiftPoke/Info.plist", key: "CFBundleVersion")



end
end
